version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432" # Expose port 5432 on the host to the container's port 5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-myuser}
      POSTGRES_DB: ${POSTGRES_DB:-mydatabase}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-mypassword}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: